name: Deploy to Production
on: push

jobs:
  Lint-project:
    name: Lint the project
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Runs Lint command
        run: npm run lint
  Test-project:
    name: Test the project
    runs-on: ubuntu-latest
    needs: Lint-project
    steps:
      - name: Setup project
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  Deploy-project:
    name: Deploy the project
    runs-on: ubuntu-latest
    needs: Test-project
    steps:
      - name: Setup project
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy project in host
        run: echo "Deploying..."
