name: Output Event details on issues
on: issues
jobs:
  Show-information:
    name: Show Event details in shell
    runs-on: ubuntu-latest
    steps:
      - name: Show information about the event
        run: echo "${{ toJson(github.event)}}"
